export const navLinks = [
	{
		name: "Home",
		href: "/",
		cta: false,
		showScrollToTop: true,
	},
	{
		name: "Councils",
		href: "/councils",
		cta: false,
		showScrollToTop: true,
	},
	{
		name: "Gallery",
		href: "/gallery",
		cta: false,
		showScrollToTop: true,
	},
	{
		name: "Information",
		href: "/info",
		cta: false,
		showScrollToTop: true,
	},
	{
		name: "Allocations",
		href: "/allocations",
		cta: false,
		showScrollToTop: false,
	},
	{
		name: "Team",
		href: "/team",
		cta: false,
		showScrollToTop: true,
	},
	{
		name: "Contact Us",
		href: "/contact",
		cta: false,
		showScrollToTop: false,
	},
	{
		name: "Register",
		href: "/register",
		cta: true,
		showScrollToTop: true,
	},
];

export const councils = [
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "Second Assembly",
		id: "second-assemlby",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
	{
		name: "General Assembly",
		id: "general-assembly",
		desc: "The United Nations General Assembly Second Committee is one of the six main committees of the United Nations General Assembly. The objective of this Council is to deal with finance and economic matters.",
		href: "#",
		src: "/councils/un.svg",
		alt: "United Nations Council Logo",
	},
];
